export const NAV_ITEMS = ["Entdecken", "Jobs", "Firmen", "Community", "Profil"];

export const WAITLIST_URL =
  "https://2dc38334.sibforms.com/serve/MUIFAPKpOnstY_-htfpGf8fSuN_3L6kSak_nq5bhpByLgceCY8Y4ELFy6yuneqI_G573gDtR1KAmb5Fkk7WHrhGXc3Ymc91KV9F95wvezX667FuUj-Q0XPJKutk5kc11IMYiH8umCTSuum50v4T5evlteY7oFAwPo05t1ZzxiUOtcTggYVSF4FtdLP1TZBYHjqLXC8vnMXFOX0hNlA==";

export const JOBS = [
  { id: 1, title: "UX Researcher", company: "Klara GmbH", tags: ["Remote", "Flexible Zeiten", "Ruhiges Büro", "Kein Open Space"], type: "Vollzeit", color: "#7C9E87", match: 94, desc: "Wir suchen jemanden, der mit echtem Einfühlungsvermögen Nutzerbedürfnisse erforscht. Kein Daily-Standup-Zwang, async-first." },
  { id: 2, title: "Backend Entwickler:in", company: "Softalpha", tags: ["Hybrid", "Masking-frei", "ADHS-freundlich", "Ruhezonen"], type: "Teilzeit möglich", color: "#8B7EC8", match: 87, desc: "Python/Django. Wir kommunizieren schriftlich, Meetings nur wenn nötig. Du darfst Kopfhörer tragen, dich bewegen, deinen Rhythmus leben." },
  { id: 3, title: "Grafikdesign & Illustration", company: "Bunte Welt Verlag", tags: ["Vollständig Remote", "Async", "Flexible Deadlines", "Keine Kamera-Pflicht"], type: "Freelance", color: "#D4956A", match: 81, desc: "Kinderbuchillustrationen und Marketingmaterial. Wir respektieren deine Energie und arbeiten mit klaren, schriftlichen Briefings." },
  { id: 4, title: "Data Analyst:in", company: "GreenStats AG", tags: ["Remote", "Einzelbüro möglich", "Reizarme Umgebung"], type: "Vollzeit", color: "#5B9BAD", match: 76, desc: "Nachhaltigkeitsdaten analysieren und visualisieren. Kleines Team, flache Hierarchie, du bekommst klare Aufgaben mit Kontext." },
];

export const COMPANIES = [
  { id: 1, name: "Klara GmbH", sector: "UX & Design", badge: "Zertifiziert inklusiv", checks: ["Neurodivergenz-Awareness-Training", "Flexible Arbeitszeiten", "Ruhezonen im Büro", "Async-First Kommunikation", "Individuelle Onboarding-Pläne"], employees: "45–60", color: "#7C9E87" },
  { id: 2, name: "Softalpha", sector: "Software & IT", badge: "ADHS-freundlich", checks: ["Kein Masking erwartet", "Kopfhörer-freundlich", "Schriftliche Kommunikation bevorzugt", "Reizarme Meetingräume"], employees: "20–35", color: "#8B7EC8" },
  { id: 3, name: "auticon Deutschland", sector: "IT-Consulting", badge: "Spezialisiert auf Autismus", checks: ["Von Autisten gegründet", "100% neurodivergente Mitarbeitende", "Job-Coaches inklusive", "Individuelle Begleitung"], employees: "200+", color: "#5B9BAD" },
];

export const TAG_OPTIONS = {
  strengths_personal: [
    "Empathisch", "Analytisch", "Kreativ", "Fokussiert", "Detailorientiert", "Strategisch",
    "Zuverlässig", "Kommunikationsstark", "Strukturiert", "Lösungsorientiert",
    "Teamfähig", "Lernbereit", "Belastbar", "Verantwortungsbewusst", "Engagiert",
    "Eigeninitiative", "Sorgfältig", "Offen", "Resilienz", "Organisationstalent",
    "Zielorientiert", "Selbständig", "Geduldig", "Hyperfokus", "Mustererkennung",
    "Außergewöhnliche Detailwahrnehmung", "Ehrlich und direkt", "Tiefes Fachwissen",
    "Ausdauer bei Interessen", "Kreatives Querdenken", "Hohe Konzentrationsfähigkeit",
    "Systemdenken", "Durchhaltevermögen",
  ],
  strengths_professional: [
    "Research", "UX Design", "Schreiben / Texten", "Organisation", "Projektmanagement",
    "Figma", "Canva", "Beratung", "Moderation", "Content Creation", "Konzeption",
    "Programmieren", "Datenanalyse", "Grafikdesign", "Übersetzung", "Buchhaltung",
    "Kundenbetreuung", "Lehren / Erklären", "Handwerkliche Fähigkeiten",
    "Pflege / Betreuung", "Logistik", "Qualitätssicherung", "Technischer Support",
    "Social Media", "Kommunikation", "Verwaltung",
  ],
  work_style: [
    "Async", "Schriftlich", "Mit klaren Aufgaben", "Mit viel Fokuszeit", "Eigenständig",
    "Im kleinen Team", "Remote", "Hybrid", "Mit Planbarkeit", "Kreativ frei",
    "Mit visuellen Tools", "Mit klaren Deadlines", "Mit Routinen", "Iterativ",
  ],
  communication: [
    "Schriftlich statt Telefon", "E-Mail bevorzugt", "Chat bevorzugt",
    "Keine spontanen Anrufe", "Vorab-Agenda bei Meetings", "Async statt Echtzeit",
    "Klare und direkte Sprache", "Einfache Sprache", "Visuelle Erklärungen",
    "Schriftliche Zusammenfassungen nach Meetings", "Gebärdensprache (DGS)",
    "Kommunikationshilfe / AAC", "Text-to-Speech / Screen Reader",
  ],
  assistive_tech: [
    "Screenreader (z.B. NVDA, JAWS)", "Sprachsteuerung (z.B. Dragon)",
    "Hörhilfe / Cochlea-Implantat", "Vergrößerungssoftware",
    "Tastaturbedienung statt Maus", "Ergonomische Tastatur / Maus",
    "Höhenverstellbarer Tisch", "Zeitmanagement-Apps",
    "Noise-Cancelling-Kopfhörer", "Fidget-Tools", "Rollstuhl", "Gehhilfe",
    "Kommunikationsgerät / AAC", "Gebärdensprachdolmetscher:in",
  ],
  needs: [
    "Flexible Zeiten", "Teilzeit möglich", "Remote möglich", "Hybrid möglich",
    "Asynchrone Kommunikation", "Schriftliche Kommunikation", "Klare Kommunikation",
    "Klare Prioritäten", "Klare Aufgabenbeschreibung", "Klare Deadlines",
    "Vorhersehbare Abläufe", "Feste Routinen", "Strukturierte Einarbeitung",
    "Buddy / Ansprechperson", "Job-Coaching", "Zusätzliche Check-ins",
    "Mehr Bearbeitungszeit", "Angepasste Zielvorgaben", "Flexible Pausen",
    "Zusätzliche Pausen", "Weniger Meetings", "Meetings nur mit Agenda",
    "Protokolle nach Meetings", "Aufgaben in kleinen Schritten",
    "Erinnerungen / Prompts", "Einzelgespräche statt Gruppenrunden",
    "Reizarme Umgebung", "Ruhiger Arbeitsplatz", "Einzelbüro", "Ruheraum",
    "Noise-Cancelling erlaubt", "Kopfhörer erlaubt", "Keine Kamera-Pflicht",
    "Wenig Kontextwechsel", "Ununterbrochene Fokuszeit", "Visuelle Planungs-Tools",
    "Schriftliche Briefings", "Keine spontanen Anrufe", "Vorbereitung vor Meetings",
    "Masking-freie Kultur", "Psychologische Sicherheit", "Sensorische Rücksichtnahme",
    "Reduzierte soziale Pflichttermine", "Barrierefreier Eingang", "Aufzug", "Rampe",
    "Automatische Türen", "Breite Wege / Türen", "Rollstuhlgerechter Arbeitsplatz",
    "Höhenverstellbarer Tisch", "Ergonomischer Stuhl", "Angepasste Arbeitsmittel",
    "Kurze Wege im Büro", "Parkplatz in der Nähe", "Barrierefreie Toilette",
    "Homeoffice statt Pendeln", "Screenreader-kompatible Tools",
    "Tastaturbedienbare Software", "Große Schrift", "Hoher Kontrast",
    "Vergrößerungssoftware", "Vorlesefunktionen", "Gute Beleuchtung", "Blendfreies Licht",
    "Untertitel / Captions", "Live-Transkription", "Gebärdensprachdolmetschung",
    "Schriftliche Zusammenfassungen", "Chat statt Telefon", "Visuelle Alarme",
    "Einfache Sprache", "Leichte Sprache", "Schritt-für-Schritt-Anleitungen",
    "Visuelle Anleitungen", "Mehr Zeit zum Lernen", "Flexible Startzeiten",
    "Späterer Arbeitsbeginn", "Pacing / Energiemanagement", "Sitz- und Stehoption",
    "Temperaturkontrolle", "Zugang zu Wasser / Snacks / Medikamenten",
    "Termine um Behandlungen herum", "Reduzierte Reisetätigkeit",
    "Arbeiten von zuhause bei Schub / Erschöpfung", "Weniger Lärm",
    "Weniger grelles Licht", "Parfümarme Umgebung", "Fester Sitzplatz",
    "Rückzugsort bei Überlastung",
  ],
  skills: [
    "Research", "UX", "Schreiben", "Organisation", "Projektmanagement",
    "Figma", "Canva", "Beratung", "Moderation", "Content", "Konzeption", "Kommunikation",
  ],
};

export const NEED_CATEGORIES = [
  { title: "Organisation & Kommunikation", tags: ["Flexible Zeiten", "Teilzeit möglich", "Remote möglich", "Hybrid möglich", "Asynchrone Kommunikation", "Schriftliche Kommunikation", "Klare Kommunikation", "Klare Prioritäten", "Klare Aufgabenbeschreibung", "Klare Deadlines", "Vorhersehbare Abläufe", "Feste Routinen", "Strukturierte Einarbeitung", "Buddy / Ansprechperson", "Job-Coaching", "Zusätzliche Check-ins", "Mehr Bearbeitungszeit", "Angepasste Zielvorgaben", "Flexible Pausen", "Zusätzliche Pausen", "Weniger Meetings", "Meetings nur mit Agenda", "Protokolle nach Meetings", "Aufgaben in kleinen Schritten", "Erinnerungen / Prompts", "Einzelgespräche statt Gruppenrunden"] },
  { title: "Neurodivergenz & Reizregulation", tags: ["Reizarme Umgebung", "Ruhiger Arbeitsplatz", "Einzelbüro", "Ruheraum", "Noise-Cancelling erlaubt", "Kopfhörer erlaubt", "Keine Kamera-Pflicht", "Wenig Kontextwechsel", "Ununterbrochene Fokuszeit", "Visuelle Planungs-Tools", "Schriftliche Briefings", "Keine spontanen Anrufe", "Vorbereitung vor Meetings", "Masking-freie Kultur", "Psychologische Sicherheit", "Sensorische Rücksichtnahme", "Reduzierte soziale Pflichttermine", "Weniger Lärm", "Weniger grelles Licht", "Parfümarme Umgebung", "Fester Sitzplatz", "Rückzugsort bei Überlastung"] },
  { title: "Mobilität & körperliche Barrierefreiheit", tags: ["Barrierefreier Eingang", "Aufzug", "Rampe", "Automatische Türen", "Breite Wege / Türen", "Rollstuhlgerechter Arbeitsplatz", "Höhenverstellbarer Tisch", "Ergonomischer Stuhl", "Angepasste Arbeitsmittel", "Kurze Wege im Büro", "Parkplatz in der Nähe", "Barrierefreie Toilette", "Homeoffice statt Pendeln"] },
  { title: "Sehen", tags: ["Screenreader-kompatible Tools", "Tastaturbedienbare Software", "Große Schrift", "Hoher Kontrast", "Vergrößerungssoftware", "Vorlesefunktionen", "Gute Beleuchtung", "Blendfreies Licht"] },
  { title: "Hören", tags: ["Untertitel / Captions", "Live-Transkription", "Gebärdensprachdolmetschung", "Schriftliche Zusammenfassungen", "Chat statt Telefon", "Visuelle Alarme"] },
  { title: "Lernen & Verstehen", tags: ["Einfache Sprache", "Leichte Sprache", "Schritt-für-Schritt-Anleitungen", "Visuelle Anleitungen", "Mehr Zeit zum Lernen"] },
  { title: "Energie, Gesundheit & Belastung", tags: ["Flexible Startzeiten", "Späterer Arbeitsbeginn", "Pacing / Energiemanagement", "Sitz- und Stehoption", "Temperaturkontrolle", "Zugang zu Wasser / Snacks / Medikamenten", "Termine um Behandlungen herum", "Reduzierte Reisetätigkeit", "Arbeiten von zuhause bei Schub / Erschöpfung"] },
];

export const createTagField = () => ({ tags: [], custom: "" });

export const EMPTY_PROFILE = {
  full_name: "",
  headline: "",
  bio: "",
  strengths: createTagField(),
  strengths_professional: createTagField(),
  special_interests: "",
  work_style: createTagField(),
  communication_prefs: createTagField(),
  assistive_tech: createTagField(),
  needs: createTagField(),
  skills: createTagField(),
  experience: "",
  education: "",
  languages: "",
  availability: "",
  contact_info: "",
  work_model: "",
  looking_for_work: false,
  avatar_url: "",
  has_disability_id: false,
  disability_degree: "",
  support_needs: "",
};

export const FOERDERUNGEN = [
  {
    id: "eingliederungszuschuss",
    name: "Eingliederungszuschuss",
    behoerde: "Agentur für Arbeit / Jobcenter",
    wer_beantragt: "Arbeitgeber",
    beschreibung: "Zuschuss zu den Lohnkosten bei Einstellung einer Person mit Behinderung.",
    hoehe: "Bis zu 70% des Arbeitsentgelts",
    dauer: "Bis zu 24 Monate (besonders Betroffene bis 96 Monate)",
    voraussetzung: "Behinderung oder Schwerbehinderung",
    hinweis: "Muss VOR Abschluss des Arbeitsvertrags beantragt werden!",
    relevant_for: ["alle"],
  },
  {
    id: "arbeitsassistenz",
    name: "Arbeitsassistenz",
    behoerde: "Integrationsamt",
    wer_beantragt: "Person mit Behinderung",
    beschreibung: "Finanzierung einer Assistenzperson am Arbeitsplatz.",
    hoehe: "Kostenübernahme (Rechtsanspruch ab GdB 50)",
    dauer: "Dauerhaft möglich",
    voraussetzung: "Schwerbehinderung (GdB 50+)",
    hinweis: "Anspruchsleistung — das Amt hat kein Ermessen!",
    relevant_for: ["koerper", "sinnes", "psychisch", "neurodivergenz"],
  },
  {
    id: "technische_arbeitshilfen",
    name: "Technische Arbeitshilfen & Arbeitsplatzanpassung",
    behoerde: "Integrationsamt / Reha-Träger",
    wer_beantragt: "Arbeitgeber oder Person",
    beschreibung: "Finanzierung von Hilfsmitteln, Software, ergonomischen Anpassungen, barrierefreiem Umbau.",
    hoehe: "Vollfinanzierung möglich",
    dauer: "Einmalig",
    voraussetzung: "Behinderungsbedingt notwendig",
    hinweis: "Alles was zum Arbeitsplatz gehört ist förderfähig!",
    relevant_for: ["koerper", "sinnes", "neurodivergenz"],
  },
  {
    id: "beschaeftigungssicherungszuschuss",
    name: "Beschäftigungssicherungszuschuss",
    behoerde: "Integrationsamt",
    wer_beantragt: "Arbeitgeber",
    beschreibung: "Laufender Zuschuss bei Minderleistung durch Behinderung.",
    hoehe: "Individuell nach Einzelfall",
    dauer: "Laufend",
    voraussetzung: "GdB 50+, nachgewiesene Minderleistung",
    hinweis: "Setzt voraus dass andere Fördermittel ausgeschöpft sind.",
    relevant_for: ["alle"],
  },
  {
    id: "berufsbegleitung",
    name: "Berufsbegleitung / Job-Coaching",
    behoerde: "Integrationsamt / Agentur für Arbeit",
    wer_beantragt: "Person oder Arbeitgeber",
    beschreibung: "Begleitung und Coaching am Arbeitsplatz durch Fachkräfte.",
    hoehe: "Kostenübernahme",
    dauer: "Nach Bedarf",
    voraussetzung: "Behinderung, Unterstützungsbedarf",
    hinweis: "Besonders hilfreich bei Neurodivergenz und psychischer Behinderung.",
    relevant_for: ["psychisch", "neurodivergenz", "geistig"],
  },
  {
    id: "nachteilsausgleich",
    name: "Nachteilsausgleich",
    behoerde: "Arbeitgeber / Ausbildungsstätte",
    wer_beantragt: "Person mit Behinderung",
    beschreibung: "Anpassung von Arbeitsbedingungen ohne Absenkung der fachlichen Anforderungen.",
    hoehe: "Individuell (z.B. mehr Zeit, ruhiger Raum, andere Kommunikationsform)",
    dauer: "Dauerhaft",
    voraussetzung: "Ab GdB 30 Rechtsanspruch. Auch ohne GdB mit ärztlichem Attest möglich.",
    hinweis: "Besonders relevant für ADHS, Autismus, Legasthenie, Dyskalkulie.",
    relevant_for: ["neurodivergenz", "psychisch", "sinnes", "lernen"],
  },
  {
    id: "budget_fuer_arbeit",
    name: "Budget für Arbeit",
    behoerde: "Reha-Träger / Agentur für Arbeit",
    wer_beantragt: "Arbeitgeber",
    beschreibung: "Lohnkostenzuschuss für Menschen die Anspruch auf WfbM hätten.",
    hoehe: "Bis zu 75% des Lohns",
    dauer: "Dauerhaft möglich",
    voraussetzung: "Berechtigung zur Werkstatt für Menschen mit Behinderung (WfbM)",
    hinweis: "Alternative zur Werkstatt — ermöglicht Arbeit auf dem ersten Arbeitsmarkt.",
    relevant_for: ["geistig", "psychisch"],
  },
  {
    id: "gebaerdensprache",
    name: "Gebärdensprachdolmetscher:in / Kommunikationshilfen",
    behoerde: "Integrationsamt",
    wer_beantragt: "Person oder Arbeitgeber",
    beschreibung: "Kostenübernahme für Dolmetscher:innen oder andere Kommunikationshilfen.",
    hoehe: "Kostenübernahme (neue Stundensätze ab 04/2025)",
    dauer: "Nach Bedarf",
    voraussetzung: "Hörbehinderung oder Kommunikationsbeeinträchtigung",
    hinweis: "Auch für Video-Meetings und Schulungen beantragbar.",
    relevant_for: ["sinnes"],
  },
  {
    id: "eutb",
    name: "EUTB — Ergänzende Unabhängige Teilhabeberatung",
    behoerde: "Bundesweit, kostenlos",
    wer_beantragt: "Person mit Behinderung",
    beschreibung: "Kostenlose unabhängige Beratung zu allen Förderungen und Rechten.",
    hoehe: "Kostenlos",
    dauer: "Kostenlos, jederzeit",
    voraussetzung: "Keine — für alle Menschen mit Behinderung oder drohender Behinderung",
    hinweis: "Empfehlung: Immer zuerst hier beraten lassen um die richtigen Träger zu finden!",
    relevant_for: ["alle"],
  },
];
